<h3>Users</h3>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Email</th>
        <th>&nbsp;&nbsp;</th>
    </tr>
    <?php foreach ($users as $user) { ?>
    <tr>
        <td><?php echo $this->escapeHtml($user->name); ?></td>
        <td><?php echo $this->escapeHtml($user->email); ?></td>
        <td>
            <a href="<?php echo $this->url('users/user-manager', array('action'=>'edit','id'=>$user->user_id)); ?>">Edit</a> |
            <a href="<?php echo $this->url('users/user-manager', array('action'=>'delete','id'=>$user->user_id)); ?>" onclick="return confirm('Are you sure?')">Delete</a>
        </td>
    </tr>
    <?php } ?>
</table>