<?php

$title = 'Edit Role';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'mhr-acl/default',
    array(
        'id'     => $this->id,
        'action'     => 'edit',
        'controller' => 'role'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
