<h1>Registration</h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('mhr-user/default', array('controller' => 'register', 'action' => 'index')));
$form->prepare();

echo $this->form()->openTag($form);

//echo $this->formRow($form->get('username'));
//echo $this->formRow($form->get('email'));
//echo $this->formRow($form->get('password'));
//echo $this->formRow($form->get('passwordVerify'));
//echo $this->formRow($form->get('captcha'));
//echo $this->formSubmit($form->get('submit'));

echo $this->formCollection($form);
echo $this->form()->closeTag();

?>