<div>
    <div>
        <div>
            <div>
                <h3>Roles</h3>
            </div>
            <div>
                <a href="<?php echo $this->url('mhr-role', array('action'=>'add'));?>">Add Role</a>

                <?php if (isset($roles)) : ?>
                    <table>
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Full name</th>
                            <th></th>
                        </tr>
                        </thead>
                        <?php foreach($roles as $role): ?>
                            <tbody>
                            <tr>
                                <td><?php echo $role->getId(); ?></td>
                                <td><?php echo $role->getRoleName(); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('mhr-role', array('action'=>'edit', 'id' => $role->getId()));?>">Edit</a> |
                                    <a href="<?php echo $this->url('mhr-role', array('action'=>'delete', 'id' => $role->getId()));?>">Delete</a>
                                </td>
                            </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>