<hgroup id="login-title" class="large-margin-bottom">
        <h1 class="login-title-image">Developr</h1>
        <h5>&copy; rilwanfit@gmail.com</h5>
</hgroup>

    <?php if($this->error): ?>
    <p class="error">
        There were one or more issues with your submission. Please correct them as indicated below.
    </p>
    <?php endif;?>
    <?php
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action', $this->url(NULL, array('controller'=>'login', 'action'=>'process')));
    $form->setAttribute('method', 'post');
    $form->setAttribute('id', 'form-login');
    echo $this->form()->openTag($form);
    ?>
    <ul class="inputs black-input large">
                <!-- The autocomplete="off" attributes is the only way to prevent webkit browsers from filling the inputs with yellow -->
                <li><span class="icon-user mid-margin-right"></span>
                    <?php echo $this->formElement($form->get('email')); ?>
            <?php echo $this->formElementErrors($form->get('email')); ?>
                    </li>
                <li><span class="icon-lock mid-margin-right"></span>
                    <?php echo $this->formElement($form->get('password')); ?>
            <?php echo $this->formElementErrors($form->get('password')); ?>
        </ul>

        <!--<button type="submit" class="button glossy full-width huge">Login</button>-->

            <?php echo $this->formElement($form->get('submit')); ?>
            <?php echo $this->formElementErrors($form->get('submit')); ?>
    <?php echo $this->form()->closeTag($form); ?>
<a href="/users">Back to user module.</a>