<h3>User Role Editor</h3>
<p>Select role and its capabilities in the list.</p>
<div>Select Role :</div>
<h3>Capabilities</h3>


<?php

$form = $this->form;
$form->setAttribute('action', $this->url(
    'mhr-acl/default',
    array(
        'action'     => 'add',
        'controller' => 'role'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>
