<div>
    <div>
        <div>
            <div>
                <h3>Users</h3>
            </div>
            <div>
                <a href="<?php echo $this->url('mhr-user', array('action'=>'add'));?>">Add User</a>

                <?php if (isset($users)) : ?>
                    <table>
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Full name</th>
                            <th></th>
                        </tr>
                        </thead>
                        <?php foreach($users as $user): ?>
                            <tbody>
                            <tr>
                                <td><?php echo $user->getId(); ?></td>
                                <td><?php echo $user->getFirstName(); ?></td>
                                <td>
                                    <a href="<?php echo $this->url('mhr-user', array('action'=>'edit', 'id' => $user->getId()));?>">Edit</a> |
                                    <a href="<?php echo $this->url('mhr-user', array('action'=>'delete', 'id' => $user->getId()));?>">Delete</a>
                                </td>
                            </tr>
                            </tbody>
                        <?php endforeach; ?>
                    </table>
                <?php endif; ?>
            </div>
        </div>
    </div>
</div>