<!-- h1>I am in AuthDoctrine IndexController login action index.phtml</h1 -->
<?php echo $this->messages; ?>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'mhr-user/default',
    array(
        'action'     => 'login',
        'controller' => 'index'
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

?>

<?php // view helper
try {
    if ($user = $this->identity()) {
        echo 'Logged in as ' . $this->escapeHtml($user->getUsrName());
        ?>
        | <a href="<?php echo $this->url('mhr-user/default', array('controller' => 'index', 'action' => 'logout'));?>"><?php echo $this->translate('Logout'); ?></a>
    <?php
    } else {
        echo 'Not logged in';
    }
} catch(Exception $e) {
    echo $e->getMessage();
}
?>

<p>
    <a href="<?php echo $this->url('mhr-user/default', array('controller' => 'register', 'action' => 'index'));?>"><?php echo $this->translate('Register'); ?></a> |
    <a href="<?php echo $this->url('mhr-user/default', array('controller' => 'index', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Forgotten Password'); ?></a>
</p>